### ISSUE TITLE
Date and Time Standards

### ISSUE THREAD

**Issue by bbethell-1** [redhat-cop/babylon#360]
As discussed with @aleixhub  and the team today on the CoG call. 

Please can we make the time have a timezone or make it clear that it's the users local time?

Also with the date, as @9strands mentioned the date standard can vary for US and Europe - please can this also be made clear for the end user? 
Thank you

**Comment by aleixhub** [comment]
Addressed in https://github.com/redhat-cop/babylon/pull/361. Now it will include the timezone

Regarding the date format that will be picked from the browser locale. For example: if the user has the browser in en-US the format will be month/day/year. If is es-ES then will be day/month/year
